// HerTech — Reactions view, organic chemistry, NCERT content

// ===== REACTIONS =====
var reactions=[
  {id:'na_water',title:'Sodium + Water',eq:'2Na + 2H₂O → 2NaOH + H₂↑',type:'Displacement',color:'#f97316',
   voice:'Sodium metal reacts vigorously with water in a displacement reaction, forming sodium hydroxide and hydrogen gas. The reaction is highly exothermic, meaning it releases heat. The hydrogen gas produced may ignite, causing a flame or explosion. Sodium is always stored in oil to prevent contact with moisture.',
   steps:['Sodium metal placed in water','Vigorous fizzing — H₂ gas forms','Sodium skates on surface (gas propulsion)','Yellow flame may appear — H₂ igniting','White NaOH solution remains'],
   ncert:'<b>Type:</b> Displacement. 2Na + 2H₂O → 2NaOH + H₂↑<br>Stored in oil (reacts with moisture). Reactivity: Li < Na < K. Alkali metals get more reactive down the group.',
   anim:'explosion'},
  {id:'h2_o2',title:'Hydrogen + Oxygen → Water',eq:'2H₂ + O₂ → 2H₂O',type:'Combination',color:'#06b6d4',
   voice:'Hydrogen gas reacts with oxygen gas to form water. This combination reaction releases a tremendous amount of energy as heat and light. It is the basis of hydrogen fuel cells, which power zero-emission vehicles. The bond energy released exceeds that absorbed, making this highly exothermic at 572 kilojoules per mole.',
   steps:['H₂ (colourless) + O₂ in air present','Spark or flame initiates reaction','C–H bonds break, O=O breaks','New O–H bonds form (very strong)','Water vapour condenses to liquid'],
   ncert:'<b>Type:</b> Combination/Combustion. 2H₂ + O₂ → 2H₂O. ΔH = −572 kJ/mol. Basis of H₂ fuel cells. H–H bond: 436 kJ/mol, O=O: 498 kJ/mol, O–H: 463 kJ/mol.',
   anim:'burn'},
  {id:'hcl_naoh',title:'HCl + NaOH (Neutralization)',eq:'HCl + NaOH → NaCl + H₂O',type:'Neutralization',color:'#06b6d4',
   voice:'When hydrochloric acid reacts with sodium hydroxide, a neutralization reaction occurs. The acid and base cancel each other out to form table salt and water. The ionic equation shows H-plus ions combining with OH-minus ions to form water. The reaction releases 57 kilojoules per mole and the final solution has a pH of 7.',
   steps:['HCl (acid, red litmus) + NaOH (base)','H⁺ ions meet OH⁻ ions','Neutralization: H⁺ + OH⁻ → H₂O','pH changes from acidic to 7','NaCl (table salt) remains in solution'],
   ncert:'<b>Type:</b> Neutralization. Ionic: H⁺(aq) + OH⁻(aq) → H₂O(l). ΔH = −57.1 kJ/mol. Litmus turns purple at equivalence point. Used in antacids, titrations.',
   anim:'neutralize'},
  {id:'na_cl',title:'Sodium + Chlorine → Salt',eq:'2Na + Cl₂ → 2NaCl',type:'Ionic Bond Formation',color:'#10b981',
   voice:'Sodium reacts with chlorine to form sodium chloride — ordinary table salt. Sodium loses one electron to become Na-plus, and chlorine gains that electron to become Cl-minus. This electron transfer creates an ionic bond. The resulting compound has completely different properties: sodium is explosive, chlorine is toxic, but NaCl is completely safe.',
   steps:['Na (silvery metal) + Cl₂ (yellow-green gas)','Na loses 3s¹ electron: Na → Na⁺ + e⁻','Cl gains electron: Cl + e⁻ → Cl⁻','Electrostatic attraction forms ionic bond','NaCl crystallizes as white cubic lattice'],
   ncert:'<b>Type:</b> Combination/Ionic. Na → Na⁺ ([Ne] config) + e⁻. Cl + e⁻ → Cl⁻ ([Ar] config). Lattice energy NaCl = 787 kJ/mol. Example of ionic bond formation via electron transfer.',
   anim:'ionic'},
  {id:'ch4_burn',title:'Methane Combustion',eq:'CH₄ + 2O₂ → CO₂ + 2H₂O',type:'Combustion',color:'#ef4444',
   voice:'Methane undergoes complete combustion in the presence of excess oxygen to form carbon dioxide and water vapour. This reaction releases 890 kilojoules per mole, making natural gas an excellent fuel. Incomplete combustion produces toxic carbon monoxide. All hydrocarbons follow the formula C-n H-2n-plus-2 and burn completely to form CO2 and water.',
   steps:['CH₄ gas (colourless) + O₂ in air','Spark ignites — C–H bonds break','C oxidised → CO₂; H oxidised → H₂O','Blue flame visible — exothermic','CO₂ turns limewater milky (test)'],
   ncert:'<b>Type:</b> Combustion. CₙH₂ₙ₊₂ + excess O₂ → nCO₂ + (n+1)H₂O. ΔH = −890 kJ/mol for CH₄. Incomplete: 2CH₄ + 3O₂ → 2CO + 4H₂O (toxic!). Class 12 organic — hydrocarbons.',
   anim:'burn'},
  {id:'electrolysis',title:'Electrolysis of Water',eq:'2H₂O → 2H₂ + O₂ (electricity)',type:'Electrolytic Decomposition',color:'#8b5cf6',
   voice:'During electrolysis, electrical energy is used to decompose water into hydrogen and oxygen gases. Hydrogen is released at the cathode — the negative electrode — because positively charged hydrogen ions are attracted to it. Oxygen is released at the anode — the positive electrode. The volume ratio of hydrogen to oxygen produced is always 2 to 1, confirming Faraday\'s laws.',
   steps:['Water + dilute H₂SO₄ (electrolyte)','Electric current applied to electrodes','Cathode: 2H₂O + 2e⁻ → H₂ + 2OH⁻','Anode: 2H₂O → O₂ + 4H⁺ + 4e⁻','H₂:O₂ volume ratio = 2:1 (Faraday law)'],
   ncert:'<b>Type:</b> Electrolytic Decomposition (Class 12 Electrochemistry). Faraday Law: m = ZIt. 96485 C deposits 1 gram-equivalent. Non-spontaneous reaction driven by electrical energy.',
   anim:'electrolysis'},
];

var curRx=null,rxAF=null;
function initReactions(){
  document.getElementById('rxList').innerHTML=reactions.map(function(rx,i){
    return'<div class="rx-item" id="rxi'+i+'" onclick="selectRx('+i+')">'+'<div class="rx-item-title">'+rx.title+'</div><div class="rx-item-eq">'+rx.eq+'</div>'+'<div class="rx-item-type" style="background:'+rx.color+'22;color:'+rx.color+';border:1px solid '+rx.color+'44;">'+rx.type+'</div></div>';
  }).join('');
}
initReactions();

function selectRx(i){
  var rx=reactions[i];curRx=rx;
  document.querySelectorAll('.rx-item').forEach(function(el,j){el.classList.toggle('on',j===i);});
  var main=document.getElementById('rxMain');
  main.innerHTML='<div><div style="display:flex;align-items:flex-start;justify-content:space-between;flex-wrap:wrap;gap:10px;">'+'<div><div style="font-size:20px;font-weight:800;margin-bottom:4px;">'+rx.title+'</div>'+'<div style="font-size:10px;margin-bottom:8px;"><span style="background:'+rx.color+'22;color:'+rx.color+';border:1px solid '+rx.color+'44;padding:2px 8px;border-radius:4px;">'+rx.type+'</span></div>'+'<div class="rx-eq-box">'+rx.eq+'</div></div>'+'<div style="display:flex;gap:8px;flex-wrap:wrap;">'+'<button class="voice-btn" id="rxVBtn" onclick="speakRx()">🔊 Hear Explanation</button>'+'<button class="voice-btn" style="background:var(--s2);color:var(--text);" onclick="stopSpeech()">⏹ Stop</button></div></div>'+'<canvas class="rxcv" id="rxCv"></canvas>'+'<div><div class="ict" style="margin-bottom:8px;">Step-by-Step Process</div><div class="rx-steps">'+rx.steps.map(function(s,si){return'<div class="rx-step"><div class="rx-sn">'+(si+1)+'</div><div style="font-size:12px;line-height:1.5;">'+s+'</div></div>';}).join('')+'</div></div>'+'<div><div class="ict" style="margin-bottom:8px;">📜 Voice Script</div><div style="background:rgba(99,102,241,.05);border:1px solid rgba(99,102,241,.12);border-radius:8px;padding:12px;font-size:12px;line-height:1.7;font-style:italic;">'+rx.voice+'</div></div>'+'<div><div class="ict" style="margin-bottom:8px;">📚 NCERT Notes</div><div class="ncert-note">'+rx.ncert+'</div></div></div>';
  setTimeout(function(){playRxAnim(rx);},80);
}

function speakRx(){
  if(!curRx)return;
  stopSpeech();
  var utt=new SpeechSynthesisUtterance(curRx.voice);
  function go(){var voices=window.speechSynthesis.getVoices();var mv=voices.find(function(v){return v.name.includes('Male')||v.name.includes('David')||v.name.includes('Daniel')||v.name.includes('Hemant');});if(!mv)mv=voices.find(function(v){return v.lang==='en-GB'||v.lang==='en-US';});if(mv)utt.voice=mv;utt.rate=0.88;utt.pitch=0.95;utt.volume=1;window.speechSynthesis.speak(utt);}
  if(window.speechSynthesis.getVoices().length===0){window.speechSynthesis.onvoiceschanged=go;}else{go();}
}
function stopSpeech(){if(window.speechSynthesis.speaking)window.speechSynthesis.cancel();}

function playRxAnim(rx){
  if(rxAF)cancelAnimationFrame(rxAF);
  var cv=document.getElementById('rxCv');if(!cv)return;
  cv.width=cv.offsetWidth||600;cv.height=300;
  var ctx=cv.getContext('2d');var W=cv.width,H=cv.height,cx=W/2,cy=H/2;
  var t=0;var particles=[];
  function addP(x,y,vx,vy,r,col,life){particles.push({x:x,y:y,vx:vx,vy:vy,r:r,c:col,l:life,ml:life});}
  function fr(){
    t++;ctx.fillStyle='rgba(0,12,30,.2)';ctx.fillRect(0,0,W,H);
    var type=rx.anim;
    if(type==='explosion'){
      ctx.fillStyle='rgba(0,80,180,.25)';ctx.fillRect(0,cy+20,W,H-cy-20);
      if(t%3===0)for(var pi=0;pi<3;pi++){addP(cx+(Math.random()-.5)*60,cy+15,(Math.random()-.5)*5,-Math.random()*7-1,2+Math.random()*3,'#fbbf24',60);}
      ctx.fillStyle='rgba(180,180,120,.9)';ctx.fillRect(cx-22,cy+5,44,26);
      ctx.fillStyle='#fff';ctx.font='bold 11px Space Mono';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('Na',cx,cy+18);ctx.textBaseline='alphabetic';
      if(t>18){var fl=20+Math.sin(t*.35)*12;ctx.fillStyle='rgba(255,160,0,.7)';ctx.beginPath();ctx.ellipse(cx,cy+5,15,fl,0,0,Math.PI*2);ctx.fill();}
      if(t>12){ctx.fillStyle='rgba(0,229,255,.7)';ctx.font='10px Inter';ctx.textAlign='center';ctx.fillText('H₂ ↑',cx,cy-25);}
    }else if(type==='burn'){
      if(t%2===0)for(var fi=0;fi<6;fi++){addP(cx+(Math.random()-.5)*28,cy-5,(Math.random()-.5)*4,-Math.random()*7-1,2+Math.random()*3,'#fff',55);}
      ctx.fillStyle='rgba(120,90,60,.5)';ctx.fillRect(cx-5,cy+10,10,55);
      var glow=ctx.createRadialGradient(cx,cy-5,0,cx,cy,85+Math.sin(t*.22)*20);glow.addColorStop(0,'rgba(255,255,255,.45)');glow.addColorStop(.25,'rgba(255,200,0,.2)');glow.addColorStop(1,'transparent');
      ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);
    }else if(type==='neutralize'){
      var ph=Math.max(7,14-Math.min(t/280,1)*7);var hue=ph<7?0:(ph===7?120:240);
      ctx.fillStyle='hsla('+hue+',60%,45%,.3)';ctx.fillRect(cx-65,cy-45,130,90);ctx.strokeStyle='rgba(255,255,255,.15)';ctx.lineWidth=1;ctx.strokeRect(cx-65,cy-45,130,90);
      ctx.fillStyle='#fff';ctx.font='13px Inter';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('pH ≈ '+Math.round(ph),cx,cy);ctx.textBaseline='alphabetic';
      if(t%8===0)addP(cx+(Math.random()-.5)*40,cy-35,(Math.random()-.5),-Math.random()*1.5,2,'#60a5fa',50);
    }else if(type==='ionic'){
      var prog=Math.min(1,t/200);var naX=cx-90+prog*55,clX=cx+90-prog*50;
      var ng=ctx.createRadialGradient(naX,cy,0,naX,cy,26);ng.addColorStop(0,'#fff');ng.addColorStop(.4,'#fca5a5');ng.addColorStop(1,'#ef444444');
      ctx.beginPath();ctx.arc(naX,cy,26,0,Math.PI*2);ctx.fillStyle=ng;ctx.fill();
      ctx.fillStyle='#1a202c';ctx.font='bold 12px Space Mono';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('Na',naX,cy);
      var cg=ctx.createRadialGradient(clX,cy,0,clX,cy,24);cg.addColorStop(0,'#fff');cg.addColorStop(.4,'#fde68a');cg.addColorStop(1,'#eab30844');
      ctx.beginPath();ctx.arc(clX,cy,24,0,Math.PI*2);ctx.fillStyle=cg;ctx.fill();
      ctx.fillStyle='#1a202c';ctx.fillText('Cl',clX,cy);ctx.textBaseline='alphabetic';
      if(prog>.3&&prog<.7){var ePct=(prog-.3)/.4;var ex=naX+(clX-naX)*ePct;ctx.fillStyle='#00e5ff';ctx.beginPath();ctx.arc(ex,cy-28,5,0,Math.PI*2);ctx.fill();}
      if(prog>.75){ctx.fillStyle='rgba(255,255,255,.7)';ctx.font='12px Inter';ctx.textAlign='center';ctx.fillText('Na⁺  Cl⁻  →  NaCl',cx,cy+55);}
    }else if(type==='electrolysis'){
      ctx.fillStyle='rgba(0,100,180,.25)';ctx.fillRect(cx-75,cy-35,150,80);
      ctx.fillStyle='#888';ctx.fillRect(cx-55,cy-55,7,65);ctx.fillRect(cx+48,cy-55,7,65);
      ctx.fillStyle='rgba(0,229,255,.85)';ctx.font='9px Space Mono';ctx.textAlign='center';ctx.fillText('(-) Cathode',cx-52,cy-62);
      ctx.fillStyle='rgba(249,115,22,.85)';ctx.fillText('(+) Anode',cx+52,cy-62);
      if(t%3===0){addP(cx-52,cy-35,(Math.random()-.5),-Math.random()*2,2.5,'#86efac',45);addP(cx-52,cy-35,(Math.random()-.5),-Math.random()*2,2.5,'#86efac',45);}
      if(t%5===0)addP(cx+52,cy-35,(Math.random()-.5),-Math.random()*2,2.5,'#fb923c',45);
      ctx.fillStyle='rgba(134,239,172,.8)';ctx.fillText('H₂ ↑',cx-52,cy-85);
      ctx.fillStyle='rgba(251,146,60,.8)';ctx.fillText('O₂ ↑',cx+52,cy-85);
      ctx.fillStyle='rgba(255,215,0,.75)';ctx.font='11px Inter';ctx.fillText('⚡ DC Current',cx,cy+65);
    }
    particles=particles.filter(function(p){return p.l>0;});
    particles.forEach(function(p){p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.l--;var al=Math.max(0,p.l/p.ml);ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.5,p.r*al),0,Math.PI*2);ctx.fillStyle=p.c+(('0'+Math.round(al*255).toString(16)).slice(-2));ctx.fill();});
    ctx.fillStyle='rgba(255,255,255,.88)';ctx.font='bold 11px Space Mono';ctx.textAlign='center';ctx.fillText(rx.eq,W/2,16);
    rxAF=requestAnimationFrame(fr);
  }fr();
}

// ===== ORGANIC CHEMISTRY =====
var orgData={
  methane:{title:'Methane',formula:'CH₄',hybrid:'sp³',angle:'109.5°',intro:'Simplest alkane (saturated hydrocarbon). Tetrahedral geometry. Natural gas — primary fuel.',
    props:[{l:'Molecular Formula',v:'CH₄'},{l:'Hybridization',v:'sp³'},{l:'Bond Angle',v:'109.5°'},{l:'State @ STP',v:'Gas'},{l:'Boiling Point',v:'−161°C'},{l:'Molar Mass',v:'16.04 g/mol'}],
    reactions:[{name:'Complete Combustion',eq:'CH₄ + 2O₂ → CO₂ + 2H₂O',cond:'Excess O₂',desc:'Exothermic, ΔH = −890 kJ/mol. Blue flame. Products are CO₂ and water.'},{name:'Free Radical Halogenation',eq:'CH₄ + Cl₂ → CH₃Cl + HCl',cond:'UV light (hν)',desc:'Free radical substitution — Initiation, Propagation, Termination.'},{name:'Steam Reforming',eq:'CH₄ + H₂O → CO + 3H₂',cond:'Ni catalyst, 700°C',desc:'Industrial H₂ production. CO is a side product (toxic).'}],
    voice:'Methane is the simplest organic compound — one carbon bonded to four hydrogen atoms in a perfect tetrahedral shape. It is the main component of natural gas and burns with a blue flame to produce carbon dioxide and water. The carbon in methane is sp3 hybridized with bond angles of 109.5 degrees.',
    atoms:[{s:'C',x:.5,y:.5,r:18,c:'#86efac'},{s:'H',x:.26,y:.28,r:11,c:'#e2e8f0'},{s:'H',x:.74,y:.28,r:11,c:'#e2e8f0'},{s:'H',x:.26,y:.72,r:11,c:'#e2e8f0'},{s:'H',x:.74,y:.72,r:11,c:'#e2e8f0'}]},
  ethane:{title:'Ethane',formula:'C₂H₆',hybrid:'sp³',angle:'109.5°',intro:'Second alkane (C₂H₂ₙ₊₂, n=2). Free rotation about C–C bond. Found in natural gas.',
    props:[{l:'Formula',v:'C₂H₆'},{l:'Hybridization',v:'sp³'},{l:'Bond Angle',v:'109.5°'},{l:'State',v:'Gas'},{l:'BP',v:'−89°C'}],
    reactions:[{name:'Combustion',eq:'2C₂H₆ + 7O₂ → 4CO₂ + 6H₂O',cond:'Excess O₂',desc:'Complete combustion of ethane.'},{name:'Halogenation',eq:'C₂H₆ + Cl₂ → C₂H₅Cl + HCl',cond:'UV light',desc:'Free radical substitution. Chloroethane forms.'}],
    voice:'Ethane has two carbon atoms each sp3 hybridized, bonded in a tetrahedral arrangement. There is free rotation about the C-C single sigma bond. Ethane undergoes combustion and halogenation reactions.',
    atoms:[{s:'C',x:.34,y:.5,r:17,c:'#86efac'},{s:'C',x:.66,y:.5,r:17,c:'#86efac'},{s:'H',x:.15,y:.35,r:10,c:'#e2e8f0'},{s:'H',x:.15,y:.65,r:10,c:'#e2e8f0'},{s:'H',x:.34,y:.25,r:10,c:'#e2e8f0'},{s:'H',x:.85,y:.35,r:10,c:'#e2e8f0'},{s:'H',x:.85,y:.65,r:10,c:'#e2e8f0'},{s:'H',x:.66,y:.25,r:10,c:'#e2e8f0'}]},
  ethene:{title:'Ethene (Ethylene)',formula:'C₂H₄',hybrid:'sp²',angle:'120°',intro:'Simplest alkene. Contains C=C double bond (1σ + 1π). Planar molecule. Important industrial chemical.',
    props:[{l:'Formula',v:'C₂H₄'},{l:'Hybridization',v:'sp²'},{l:'Bond Angle',v:'120°'},{l:'State',v:'Gas'},{l:'BP',v:'−104°C'},{l:'Bond Order',v:'2 (C=C)'}],
    reactions:[{name:'Hydrogenation',eq:'C₂H₄ + H₂ → C₂H₆',cond:'Ni/Pt catalyst',desc:'Addition reaction. Converts alkene to alkane. Used to harden vegetable oils.'},{name:'Halogenation (Bromine test)',eq:'C₂H₄ + Br₂ → CH₂Br–CH₂Br',cond:'CCl₄, room temp',desc:'Bromine water DECOLOURISES — TEST for alkene double bond!'},{name:'Hydration (Markovnikov)',eq:'C₂H₄ + H₂O → C₂H₅OH',cond:'H⁺ catalyst',desc:'Adds water across double bond. Forms ethanol (1° alcohol).'}],
    voice:'Ethene contains a carbon-carbon double bond, making it an alkene. The double bond consists of one sigma bond and one pi bond. The molecule is flat, with bond angles of 120 degrees, because carbon is sp2 hybridized. Bromine water decolourises in the presence of ethene — this is the standard test for alkenes.',
    atoms:[{s:'C',x:.34,y:.5,r:17,c:'#86efac'},{s:'C',x:.66,y:.5,r:17,c:'#86efac'},{s:'H',x:.15,y:.35,r:10,c:'#e2e8f0'},{s:'H',x:.15,y:.65,r:10,c:'#e2e8f0'},{s:'H',x:.85,y:.35,r:10,c:'#e2e8f0'},{s:'H',x:.85,y:.65,r:10,c:'#e2e8f0'}]},
  ethyne:{title:'Ethyne (Acetylene)',formula:'C₂H₂',hybrid:'sp',angle:'180°',intro:'Simplest alkyne. Contains C≡C triple bond (1σ + 2π). Linear geometry. Burns at 3500°C.',
    props:[{l:'Formula',v:'C₂H₂'},{l:'Hybridization',v:'sp'},{l:'Bond Angle',v:'180° (linear)'},{l:'State',v:'Gas'},{l:'BP',v:'−84°C'},{l:'Bond Order',v:'3 (C≡C)'}],
    reactions:[{name:'Hydrogenation (Full)',eq:'HC≡CH + 2H₂ → CH₃–CH₃',cond:'Ni, high pressure',desc:'Two-step: alkyne → alkene → alkane. Lindlar catalyst stops at alkene.'},{name:'Hydration (Kucherov)',eq:'HC≡CH + H₂O → CH₃CHO',cond:'H₂SO₄/HgSO₄',desc:'Vinyl alcohol (enol) rearranges to acetaldehyde (keto-enol tautomerism).'},{name:'Acidic Nature',eq:'HC≡CH + NaNH₂ → HC≡CNa + NH₃',cond:'Liquid NH₃',desc:'Terminal H is weakly acidic (pKa≈25). Forms acetylide salts.'}],
    voice:'Ethyne, also called acetylene, has a carbon-carbon triple bond. The triple bond has one sigma bond and two pi bonds. Carbon is sp hybridized, giving a linear molecule with a 180-degree bond angle. The oxy-acetylene flame burns at 3500 degrees Celsius — the hottest chemical flame used in welding.',
    atoms:[{s:'C',x:.34,y:.5,r:17,c:'#86efac'},{s:'C',x:.66,y:.5,r:17,c:'#86efac'},{s:'H',x:.14,y:.5,r:10,c:'#e2e8f0'},{s:'H',x:.86,y:.5,r:10,c:'#e2e8f0'}]},
  benzene:{title:'Benzene',formula:'C₆H₆',hybrid:'sp²',angle:'120°',intro:'Aromatic compound. Delocalized π electrons. All bonds equal (140 pm). Resonance stabilized. Hückel rule: 6π electrons.',
    props:[{l:'Formula',v:'C₆H₆'},{l:'Hybridization',v:'sp²'},{l:'Bond Angle',v:'120°'},{l:'Resonance Energy',v:'150 kJ/mol'},{l:'Bond Length',v:'140 pm (all equal)'},{l:'State',v:'Liquid (colourless)'}],
    reactions:[{name:'Nitration (EAS)',eq:'C₆H₆ + HNO₃ → C₆H₅NO₂ + H₂O',cond:'Conc. H₂SO₄, 50°C',desc:'NO₂⁺ (nitronium ion) is electrophile. Forms nitrobenzene (pale yellow).'},{name:'Halogenation (EAS)',eq:'C₆H₆ + Cl₂ → C₆H₅Cl + HCl',cond:'FeCl₃ catalyst',desc:'FeCl₃ generates Cl⁺. Chlorobenzene forms via arenium ion intermediate.'},{name:'Friedel-Crafts Alkylation',eq:'C₆H₆ + CH₃Cl → C₆H₅CH₃ + HCl',cond:'AlCl₃',desc:'Carbocation electrophile attacks ring. Toluene forms.'}],
    voice:'Benzene is the parent compound of aromatic chemistry. All six carbon atoms are equivalent due to resonance — the pi electrons are delocalized around the entire ring. The molecule is perfectly flat and hexagonal with 120-degree bond angles. Benzene prefers electrophilic substitution over addition reactions, to preserve its aromatic stability.',
    atoms:[{s:'C',x:.5,y:.22,r:13,c:'#86efac'},{s:'C',x:.7,y:.35,r:13,c:'#86efac'},{s:'C',x:.7,y:.62,r:13,c:'#86efac'},{s:'C',x:.5,y:.78,r:13,c:'#86efac'},{s:'C',x:.3,y:.62,r:13,c:'#86efac'},{s:'C',x:.3,y:.35,r:13,c:'#86efac'}]},
  ethanol:{title:'Ethanol',formula:'C₂H₅OH',hybrid:'sp³ (O)',angle:'104.5° (H-O-H)',intro:'Simplest secondary functional group — alcohol. Hydroxyl group (-OH). Miscible in water. Important solvent.',
    props:[{l:'Formula',v:'C₂H₅OH'},{l:'Functional Group',v:'-OH (hydroxyl)'},{l:'Hybridization (O)',v:'sp³'},{l:'State',v:'Liquid'},{l:'BP',v:'78.4°C'},{l:'Miscible in water',v:'Yes (H-bonding)'}],
    reactions:[{name:'Oxidation (Lucas Test)',eq:'C₂H₅OH → CH₃CHO → CH₃COOH',cond:'K₂Cr₂O₇/H₂SO₄',desc:'1° alcohol → aldehyde → carboxylic acid. Orange Cr₂O₇²⁻ turns green Cr³⁺.'},{name:'Esterification',eq:'C₂H₅OH + CH₃COOH ⇌ CH₃COOC₂H₅ + H₂O',cond:'H⁺ catalyst',desc:'Ethyl acetate — fruity smell. Fischer esterification. Reversible.'},{name:'Dehydration (Elimination)',eq:'C₂H₅OH → C₂H₄ + H₂O',cond:'Conc. H₂SO₄, 170°C',desc:'E2 elimination. Ethene forms. Lower temp (140°C) → ether instead.'}],
    voice:'Ethanol is the common alcohol found in beverages. It has a hydroxyl group bonded to a two-carbon chain. Ethanol is completely miscible in water due to hydrogen bonding. Primary alcohols like ethanol oxidize to aldehydes and then to carboxylic acids. The Lucas test distinguishes alcohol classes.',
    atoms:[{s:'C',x:.28,y:.5,r:16,c:'#86efac'},{s:'C',x:.52,y:.5,r:16,c:'#86efac'},{s:'O',x:.74,y:.5,r:17,c:'#ef4444'},{s:'H',x:.88,y:.42,r:9,c:'#e2e8f0'},{s:'H',x:.14,y:.38,r:9,c:'#e2e8f0'},{s:'H',x:.14,y:.62,r:9,c:'#e2e8f0'}]},
  acetic:{title:'Acetic Acid (Ethanoic Acid)',formula:'CH₃COOH',hybrid:'sp² (carboxyl C)',angle:'120°',intro:'Simplest carboxylic acid with practical significance. Weak acid (Ka ≈ 1.8×10⁻⁵). Vinegar is 5% acetic acid.',
    props:[{l:'Formula',v:'CH₃COOH'},{l:'Functional Group',v:'-COOH (carboxyl)'},{l:'pKa',v:'4.75 (weak acid)'},{l:'State',v:'Liquid'},{l:'BP',v:'118°C'},{l:'Smell',v:'Sharp vinegar smell'}],
    reactions:[{name:'Esterification',eq:'CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O',cond:'H⁺, heat',desc:'Fischer esterification. Ethyl acetate (fruity smell) forms. Reversible.'},{name:'Decarboxylation',eq:'CH₃COONa + NaOH → CH₄ + Na₂CO₃',cond:'CaO/NaOH, heat (soda lime)',desc:'Sodium acetate heated with soda lime → methane gas. Classic lab reaction.'},{name:'HVZ Reaction',eq:'CH₃COOH + Cl₂ → ClCH₂COOH',cond:'P (red phosphorus)',desc:'Hell-Volhard-Zelinsky α-halogenation. Important for amino acid synthesis.'}],
    voice:'Acetic acid is the compound that gives vinegar its sharp taste and smell. It contains the carboxyl group, which has both a carbonyl and a hydroxyl. It is a weak acid — it only partially ionizes in water. Acetic acid undergoes esterification with alcohols to form esters, which have pleasant fruity smells.',
    atoms:[{s:'C',x:.25,y:.5,r:14,c:'#86efac'},{s:'C',x:.5,y:.5,r:16,c:'#86efac'},{s:'O',x:.5,y:.28,r:16,c:'#ef4444'},{s:'O',x:.74,y:.55,r:16,c:'#ef4444'},{s:'H',x:.88,y:.48,r:9,c:'#e2e8f0'}]},
  formaldehyde:{title:'Formaldehyde (Methanal)',formula:'HCHO',hybrid:'sp² (C)',angle:'120°',intro:'Simplest aldehyde. Highly reactive carbonyl compound. 37% aqueous solution = formalin (preservative). Carcinogenic.',
    props:[{l:'Formula',v:'HCHO'},{l:'Functional Group',v:'-CHO (aldehyde)'},{l:'Hybridization',v:'sp² (C=O carbon)'},{l:'Bond Angle',v:'120°'},{l:'State',v:'Gas (pungent)'},{l:'BP',v:'−19°C'},{l:'Molar Mass',v:'30 g/mol'}],
    reactions:[{name:'Tollens Test (Silver Mirror)',eq:'HCHO + 2[Ag(NH₃)₂]⁺ + 2OH⁻ → HCOO⁻ + 2Ag↓ + 4NH₃ + H₂O',cond:'Tollens reagent',desc:'Formaldehyde reduces Ag⁺ to metallic silver. Classic positive test for aldehydes.'},{name:'Cannizzaro Reaction',eq:'2HCHO + NaOH → HCOOH + CH₃OH',cond:'Conc. NaOH',desc:'Disproportionation — HCHO has no α-H. One oxidized to formate, one reduced to methanol.'},{name:'Polymerization',eq:'nHCHO → (CH₂O)ₙ',cond:'Acid/base catalyst',desc:'Forms trioxane (3-mer) or paraformaldehyde (polymer). Bakelite made from HCHO + phenol.'}],
    voice:'Formaldehyde is the simplest aldehyde with one carbon, one oxygen, and two hydrogens. Its carbonyl carbon is sp2 hybridized giving a 120-degree bond angle. Formaldehyde gives a positive silver mirror test because it is easily oxidized. The 37 percent aqueous solution called formalin is used to preserve biological specimens.',
    atoms:[{s:'C',x:.42,y:.5,r:16,c:'#86efac'},{s:'O',x:.7,y:.5,r:17,c:'#ef4444'},{s:'H',x:.2,y:.32,r:10,c:'#e2e8f0'},{s:'H',x:.2,y:.68,r:10,c:'#e2e8f0'}]},
  glucose:{title:'Glucose (D-Glucose)',formula:'C₆H₁₂O₆',hybrid:'sp³ (ring carbons)',angle:'109.5°',intro:'Most important monosaccharide. Primary energy source in living cells. Open-chain ↔ cyclic (pyranose) equilibrium. Reducing sugar.',
    props:[{l:'Formula',v:'C₆H₁₂O₆'},{l:'Class',v:'Monosaccharide, Aldohexose'},{l:'Hybridization',v:'sp³ (ring C atoms)'},{l:'Chiral centres',v:'4 (in open chain)'},{l:'State',v:'White solid (sweet)'},{l:'Solubility',v:'Very soluble in water'},{l:'Molar Mass',v:'180 g/mol'}],
    reactions:[{name:'Fehling\'s / Benedict\'s Test',eq:'Glucose + Cu²⁺ → Gluconolactone + Cu₂O↓',cond:'Alkaline CuSO₄ solution',desc:'Reducing aldehyde reduces Cu²⁺ (blue) → Cu₂O (brick-red precipitate). Positive for glucose.'},{name:'Fermentation',eq:'C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂',cond:'Yeast (Zymase), 37°C',desc:'Glucose ferments to ethanol and CO₂. Basis of bread-making and alcohol production.'},{name:'Glycolysis (overview)',eq:'C₆H₁₂O₆ + 2ADP + 2Pi → 2 Pyruvate + 2ATP',cond:'Enzymatic (cytoplasm)',desc:'10-step metabolic pathway producing ATP. Common first step in cellular respiration.'}],
    voice:'Glucose is the most important sugar and the primary fuel of living cells. Its molecular formula is C6H12O6. It exists mainly as a six-membered ring called pyranose. Glucose is a reducing sugar — it reduces Fehling solution from blue to brick-red, which is a standard diagnostic test. Fermentation of glucose by yeast produces ethanol and carbon dioxide.',
    atoms:[{s:'C',x:.5,y:.22,r:13,c:'#86efac'},{s:'C',x:.72,y:.36,r:13,c:'#86efac'},{s:'C',x:.72,y:.62,r:13,c:'#86efac'},{s:'C',x:.5,y:.78,r:13,c:'#86efac'},{s:'C',x:.28,y:.62,r:13,c:'#86efac'},{s:'O',x:.28,y:.36,r:13,c:'#ef4444'},{s:'OH',x:.5,y:.04,r:11,c:'#fb923c'},{s:'OH',x:.88,y:.28,r:10,c:'#fb923c'},{s:'OH',x:.88,y:.7,r:10,c:'#fb923c'},{s:'OH',x:.12,y:.7,r:10,c:'#fb923c'}]},
  aspirin:{title:'Aspirin (Acetylsalicylic Acid)',formula:'C₉H₈O₄',hybrid:'sp² (aromatic + ester C)',angle:'120° (ring)',intro:'Most widely used NSAID analgesic/anti-inflammatory. Synthesised from salicylic acid. Inhibits COX enzymes. Ester functional group.',
    props:[{l:'Formula',v:'C₉H₈O₄'},{l:'Functional Groups',v:'Ester + Carboxylic acid + Aromatic ring'},{l:'Hybridization',v:'sp² (ring), sp³ (CH₃)'},{l:'Molar Mass',v:'180.16 g/mol'},{l:'State',v:'White crystalline solid'},{l:'Melting Point',v:'135°C'},{l:'pKa',v:'3.5'}],
    reactions:[{name:'Synthesis (Fischer Esterification)',eq:'C₇H₆O₃ + (CH₃CO)₂O → C₉H₈O₄ + CH₃COOH',cond:'H₃PO₄ catalyst, 85°C',desc:'Salicylic acid reacts with acetic anhydride. Ester bond formed at phenolic -OH. Classic school synthesis.'},{name:'Hydrolysis',eq:'C₉H₈O₄ + H₂O → C₇H₆O₃ + CH₃COOH',cond:'H⁺ or OH⁻, warm water',desc:'Ester bond cleaves. Aspirin decomposes in stomach — vinegar smell on old aspirin.'},{name:'COX Inhibition',eq:'Aspirin + COX → Acetylated COX (inactive)',cond:'Biological, irreversible',desc:'Aspirin irreversibly acetylates cyclooxygenase enzyme. Reduces prostaglandin synthesis → reduces pain and inflammation.'}],
    voice:'Aspirin, also called acetylsalicylic acid, is the world\'s most widely used medicine. It contains an ester functional group and a carboxylic acid group on a benzene ring. It is synthesised by reacting salicylic acid with acetic anhydride in a Fischer esterification. Aspirin relieves pain by irreversibly inhibiting the cyclooxygenase enzyme, which reduces the production of prostaglandins that cause inflammation.',
    atoms:[{s:'C',x:.5,y:.18,r:12,c:'#86efac'},{s:'C',x:.7,y:.3,r:12,c:'#86efac'},{s:'C',x:.7,y:.54,r:12,c:'#86efac'},{s:'C',x:.5,y:.68,r:12,c:'#86efac'},{s:'C',x:.3,y:.54,r:12,c:'#86efac'},{s:'C',x:.3,y:.3,r:12,c:'#86efac'},{s:'O',x:.86,y:.64,r:14,c:'#ef4444'},{s:'C',x:.14,y:.22,r:12,c:'#86efac'},{s:'O',x:.14,y:.44,r:13,c:'#ef4444'}]},
  chloroform:{title:'Chloroform (Trichloromethane)',formula:'CHCl₃',hybrid:'sp³',angle:'109.5°',intro:'Halogenated alkane. Dense colourless liquid with sweet smell. Once used as anaesthetic. Polar solvent. Reacts with NaOH (Carbylamine).',
    props:[{l:'Formula',v:'CHCl₃'},{l:'Hybridization',v:'sp³'},{l:'Bond Angle',v:'~109.5° (tetrahedral)'},{l:'State',v:'Colourless liquid'},{l:'BP',v:'61.2°C'},{l:'Density',v:'1.49 g/cm³ (denser than water)'},{l:'Molar Mass',v:'119.38 g/mol'}],
    reactions:[{name:'Oxidation in Air',eq:'2CHCl₃ + O₂ → 2COCl₂ + 2HCl',cond:'Sunlight, O₂',desc:'Slow oxidation produces phosgene (COCl₂), extremely toxic. Chloroform must be stored in dark, with 1% EtOH stabilizer.'},{name:'Reimer-Tiemann Reaction',eq:'CHCl₃ + NaOH → :CCl₂ + Cl⁻ + H₂O',cond:'Conc. NaOH',desc:'Generates dichlorocarbene (:CCl₂) which reacts with phenol to give salicylaldehyde.'},{name:'Carbylamine Reaction (Isocyanide test)',eq:'RNH₂ + CHCl₃ + 3KOH → RNC + 3KCl + 3H₂O',cond:'Alcoholic KOH',desc:'Primary amines react with CHCl₃ and KOH to give foul-smelling isocyanide (RNC). Classic test for primary amines.'}],
    voice:'Chloroform, or trichloromethane, is a halogenated organic compound with three chlorine atoms on a single carbon. It is sp3 hybridized with near-tetrahedral geometry. Chloroform is denser than water and has a sweet smell. It was the first anaesthetic used in surgery but is now known to be hepatotoxic. When stored improperly in light and air, it slowly converts to highly toxic phosgene gas.',
    atoms:[{s:'C',x:.5,y:.5,r:15,c:'#86efac'},{s:'Cl',x:.26,y:.28,r:17,c:'#fcd34d'},{s:'Cl',x:.74,y:.28,r:17,c:'#fcd34d'},{s:'Cl',x:.26,y:.72,r:17,c:'#fcd34d'},{s:'H',x:.74,y:.72,r:9,c:'#e2e8f0'}]},
  urea:{title:'Urea (Carbamide)',formula:'(NH₂)₂CO',hybrid:'sp² (C)',angle:'120° (C=O)',intro:'Simplest organic amide. Nitrogenous waste in urine. First organic compound synthesised from inorganic materials (Wöhler, 1828). Major nitrogen fertilizer.',
    props:[{l:'Formula',v:'(NH₂)₂CO (or CH₄N₂O)'},{l:'Functional Group',v:'Amide (-CO-NH₂) × 2'},{l:'Hybridization (C)',v:'sp²'},{l:'State',v:'White crystalline solid'},{l:'MP',v:'133°C (decomposes)'},{l:'Solubility',v:'Highly soluble in H₂O'},{l:'Molar Mass',v:'60 g/mol'}],
    reactions:[{name:'Biuret Formation',eq:'2(NH₂)₂CO → NH₂CONHCONH₂ + NH₃',cond:'170°C',desc:'Biuret test — purple colour with CuSO₄/NaOH. Used to detect proteins.'},{name:'Hydrolysis (urease)',eq:'(NH₂)₂CO + H₂O → CO₂ + 2NH₃',cond:'Urease enzyme or H⁺/OH⁻',desc:'In soil, urease converts urea fertilizer to ammonia. Basis of urea breath test for H. pylori.'},{name:'Wöhler Synthesis',eq:'NH₄CNO → (NH₂)₂CO',cond:'Heat (1828)',desc:'Historic synthesis of urea from ammonium cyanate — first proof that organic compounds can be made from inorganic precursors.'}],
    voice:'Urea is the simplest amide compound and the end product of protein metabolism in mammals. Its formula is NH2-CO-NH2 with the carbonyl carbon sp2 hybridized. Urea is historically important because it was the first organic compound to be synthesised in a laboratory from purely inorganic materials by Friedrich Wöhler in 1828, disproving vitalism. Today urea is the most widely used solid nitrogen fertilizer in the world.',
    atoms:[{s:'C',x:.5,y:.5,r:16,c:'#86efac'},{s:'O',x:.5,y:.28,r:17,c:'#ef4444'},{s:'N',x:.26,y:.66,r:15,c:'#60a5fa'},{s:'N',x:.74,y:.66,r:15,c:'#60a5fa'},{s:'H',x:.12,y:.56,r:9,c:'#e2e8f0'},{s:'H',x:.12,y:.78,r:9,c:'#e2e8f0'},{s:'H',x:.88,y:.56,r:9,c:'#e2e8f0'},{s:'H',x:.88,y:.78,r:9,c:'#e2e8f0'}]},
};
var orgMolAF=null;
function showOrg(key){
  document.querySelectorAll('.org-link').forEach(function(b){b.classList.toggle('on',b.getAttribute('onclick').includes("'"+key+"'"));});
  var d=orgData[key];if(!d)return;
  var m=document.getElementById('orgMain');
  m.innerHTML='<div style="font-size:22px;font-weight:800;margin-bottom:3px;">'+d.title+'</div>'+'<div style="font-family:var(--mono);font-size:14px;color:var(--yellow);background:rgba(245,158,11,.08);padding:5px 12px;border-radius:7px;display:inline-block;margin-bottom:14px;">'+d.formula+' | '+d.hybrid+' | '+d.angle+'</div>'+'<p style="font-size:12px;color:var(--muted);margin-bottom:16px;line-height:1.6;">'+d.intro+'</p>'+'<div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:16px;">'+'<div class="icard"><div class="ict">🔬 3D Model</div><canvas class="mol3d" id="orgCv"></canvas><div style="text-align:center;margin-top:7px;"><button onclick="speakOrg(\''+key+'\')" class="voice-btn" style="display:inline-flex;font-size:11px;padding:7px 14px;">🔊 Hear Explanation</button></div></div>'+'<div class="icard"><div class="ict">📐 Properties</div><div class="pg">'+d.props.map(function(p){return'<div class="pi"><div class="pl">'+p.l+'</div><div class="pv" style="font-size:10px;">'+p.v+'</div></div>';}).join('')+'</div></div></div>'+'<div class="icard"><div class="ict">⚗ Key Reactions</div>'+d.reactions.map(function(rx){return'<div class="rxn-card"><div class="rxn-name">'+rx.name+'</div><div class="rxn-eq">'+rx.eq+'</div><div style="font-size:9.5px;color:var(--a3);margin-bottom:3px;">Conditions: '+rx.cond+'</div><div class="rxn-desc">'+rx.desc+'</div></div>';}).join('')+'</div>';
  setTimeout(function(){drawOrgMol(d.atoms);},60);
}
function drawOrgMol(atoms){
  if(orgMolAF)cancelAnimationFrame(orgMolAF);
  var cv=document.getElementById('orgCv');if(!cv||!atoms||!atoms.length)return;
  cv.width=cv.offsetWidth||280;cv.height=200;
  var ctx=cv.getContext('2d');var ang=0;
  function fr(){ang+=0.014;ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle='rgba(0,12,30,.3)';ctx.fillRect(0,0,cv.width,cv.height);
    var cx=cv.width/2,cy=cv.height/2,sc=Math.min(cv.width,cv.height)*.38;
    for(var i=1;i<atoms.length;i++){var a0=atoms[0],ai=atoms[i];var x0=cx+(a0.x-.5)*sc*2*Math.cos(ang),y0=cy+(a0.y-.5)*sc*2;var xi=cx+(ai.x-.5)*sc*2*Math.cos(ang+.2),yi=cy+(ai.y-.5)*sc*2;var gd2=ctx.createLinearGradient(x0,y0,xi,yi);gd2.addColorStop(0,a0.c+'88');gd2.addColorStop(1,ai.c+'88');ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(xi,yi);ctx.strokeStyle=gd2;ctx.lineWidth=4;ctx.stroke();}
    atoms.forEach(function(a,idx){var ax=cx+(a.x-.5)*sc*2*Math.cos(ang+idx*.16);var ay=cy+(a.y-.5)*sc*2;var rv=a.r*(1+.08*Math.sin(ang+idx));ctx.beginPath();ctx.arc(ax+1.5,ay+2,rv,0,Math.PI*2);ctx.fillStyle='rgba(0,0,0,.25)';ctx.fill();var sg=ctx.createRadialGradient(ax-rv*.3,ay-rv*.3,rv*.07,ax,ay,rv);sg.addColorStop(0,'rgba(255,255,255,.6)');sg.addColorStop(.4,a.c);sg.addColorStop(1,a.c+'44');ctx.beginPath();ctx.arc(ax,ay,rv,0,Math.PI*2);ctx.fillStyle=sg;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.2)';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold '+(rv>11?9:7)+'px Space Mono,monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(a.s,ax,ay);});
    orgMolAF=requestAnimationFrame(fr);}
  fr();
}
function speakOrg(key){var d=orgData[key];if(!d)return;stopSpeech();var utt=new SpeechSynthesisUtterance(d.voice);function go(){var v=window.speechSynthesis.getVoices();var mv=v.find(function(x){return x.name.includes('David')||x.name.includes('Daniel')||x.name.includes('Male');});if(!mv)mv=v.find(function(x){return x.lang==='en-GB'||x.lang==='en-US';});if(mv)utt.voice=mv;utt.rate=0.88;utt.pitch=0.95;window.speechSynthesis.speak(utt);}if(window.speechSynthesis.getVoices().length===0){window.speechSynthesis.onvoiceschanged=go;}else{go();}}

// ===== MNEMONICS =====
var mnData=[
  {id:'g1',grp:'Group 1',lbl:'s-Block',els:['H','Li','Na','K','Rb','Cs','Fr'],nums:[1,3,11,19,37,55,87],col:'#ef4444',text:'H Lina ne Ki Rab Cs Fariyad',hindi:'ह लीना ने की रब से फरियाद',meaning:'H=Hydrogen, Li=Lithium, Na=Sodium, K=Potassium, Rb=Rubidium, Cs=Caesium, Fr=Francium. All Group 1 alkali metals — 1 valence electron.'},
  {id:'g2',grp:'Group 2',lbl:'s-Block',els:['Be','Mg','Ca','Sr','Ba','Ra'],nums:[4,12,20,38,56,88],col:'#f97316',text:'Beti Mange Car Scooter Baap Razi',hindi:'बेटी मांगे कार स्कूटर बाप राज़ी',meaning:'Be=Beryllium, Mg=Magnesium, Ca=Calcium, Sr=Strontium, Ba=Barium, Ra=Radium. Group 2 alkaline earth metals — 2 valence electrons.'},
  {id:'g13',grp:'Group 13',lbl:'p-Block',els:['B','Al','Ga','In','Tl','Nh'],nums:[5,13,31,49,81,113],col:'#14b8a6',text:'Bengan Alu Gazar In Thaila Neha',hindi:'बेंगन अलु गाजर एन थैला नेहा',meaning:'B=Boron, Al=Aluminium, Ga=Gallium, In=Indium, Tl=Thallium, Nh=Nihonium. Config: ns²np¹.'},
  {id:'g14',grp:'Group 14',lbl:'p-Block',els:['C','Si','Ge','Sn','Pb','Fl'],nums:[6,14,32,50,82,114],col:'#22c55e',text:'Cahe Sita Gee Suno Prabhu',hindi:'कहे सीता जी सुनो प्रभु',meaning:'C=Carbon, Si=Silicon, Ge=Germanium, Sn=Tin, Pb=Lead, Fl=Flerovium. Config: ns²np².'},
  {id:'g15',grp:'Group 15',lbl:'p-Block',els:['N','P','As','Sb','Bi','Mc'],nums:[7,15,33,51,83,115],col:'#6366f1',text:'Nana Patenkar Asweria Sab Bimar',hindi:'नाना पाटेंकर असवेरिया सब बीमार',meaning:'N=Nitrogen, P=Phosphorus, As=Arsenic, Sb=Antimony, Bi=Bismuth. Half-filled p³ — extra stability!'},
  {id:'g16',grp:'Group 16',lbl:'p-Block',els:['O','S','Se','Te','Po','Lv'],nums:[8,16,34,52,84,116],col:'#10b981',text:'O S Se Te Po',hindi:'ऊ से टी पो',meaning:'O=Oxygen, S=Sulfur, Se=Selenium, Te=Tellurium, Po=Polonium, Lv=Livermorium. Chalcogens. 6 valence electrons.'},
  {id:'g17',grp:'Group 17',lbl:'p-Block',els:['F','Cl','Br','I','At','Ts'],nums:[9,17,35,53,85,117],col:'#eab308',text:'Fir Cal Bahar AyI Aunty',hindi:'फिर कल बहार आई आंटी',meaning:'F=Fluorine, Cl=Chlorine, Br=Bromine, I=Iodine, At=Astatine, Ts=Tennessine. Halogens — most reactive nonmetals. 7 valence e⁻.'},
  {id:'g18',grp:'Group 18',lbl:'p-Block',els:['He','Ne','Ar','Kr','Xe','Rn','Og'],nums:[2,10,18,36,54,86,118],col:'#06b6d4',text:'Hena Nena Aur Karina ke Xerox Rangin',hindi:'हिना नीना और करीना के ज़ेरॉक्स रंगीन',meaning:'He=Helium, Ne=Neon, Ar=Argon, Kr=Krypton, Xe=Xenon, Rn=Radon, Og=Oganesson. Noble gases — complete shells.'},
  {id:'p4d',grp:'Period 4 (d-Block)',lbl:'d-Block',els:['Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn'],nums:[21,22,23,24,25,26,27,28,29,30],col:'#8b5cf6',text:'Science Ticher Very Cruel Mange Fees Copy Niha Cukkar Zindabad',hindi:'साइंस टीचर भीरी क्रूएल मांगे फीस कॉपी नेहा कक्कड़ जिंदाबाद',meaning:'Sc, Ti, V, Cr, Mn, Fe, Co, Ni, Cu, Zn — 1st transition series. Note: Cr=[Ar]3d⁵4s¹ and Cu=[Ar]3d¹⁰4s¹ are anomalous!'},
  {id:'g11',grp:'Group 11 (Coinage)',lbl:'d-Block',els:['Cu','Ag','Au'],nums:[29,47,79],col:'#f59e0b',text:'Cyu Aage Aau',hindi:'क्यू आगे आउ',meaning:'Cu=Copper, Ag=Silver, Au=Gold. Coinage metals. Cu and Ag have anomalous configs (full/half-filled d).'},
  {id:'g12',grp:'Group 12',lbl:'d-Block',els:['Zn','Cd','Hg'],nums:[30,48,80],col:'#6366f1',text:'Zindagi Cadbury Hogyi',hindi:'जिंदगी कैडबरी होगी',meaning:'Zn=Zinc, Cd=Cadmium, Hg=Mercury. All have d¹⁰ config. Hg is liquid at room temperature!'},
  {id:'lant',grp:'Lanthanoids',lbl:'f-Block',els:['Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu'],nums:[58,59,60,61,62,63,64,65,66,67,68,69,70,71],col:'#ec4899',text:'Cene Pr Nadiyan Prem ki Samayi Eu Gadgad Tab Dyl Ho gya Engineer Tum Yebhi Lu',hindi:'सीने पर नदियां प्रेम की समाई ईउ गदगद तब दिल हो गया इंजीनियर तुम ये भी लो',meaning:'Ce, Pr, Nd, Pm, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb, Lu. 4f electrons. Show lanthanide contraction.'},
  {id:'act',grp:'Actinoids',lbl:'f-Block',els:['Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr'],nums:[90,91,92,93,94,95,96,97,98,99,100,101,102,103],col:'#f43f5e',text:'Thor ke Papa ne U bola Nepal me Purane Am Cam Bikenge Cafe me jana Ease Farmana Madam Noodles Lare',hindi:'थोर के पापा ने बोला नेपाल में पुराने आम काम बिकेंगे कैफे में जाना ऐसे फरमान मैडम नूडल्स लारे',meaning:'Th, Pa, U, Np, Pu, Am, Cm, Bk, Cf, Es, Fm, Md, No, Lr. 5f electrons. All radioactive!'},
];
var mnVA={};
function buildMn(){
  document.getElementById('mnGrid').innerHTML=mnData.map(function(mn,i){
    return'<div class="mn-card" id="mnC'+i+'"><div class="mn-header" style="border-top:3px solid '+mn.col+'"><div><div style="font-size:12px;font-weight:700;color:'+mn.col+';">'+mn.grp+'</div><div style="font-size:9px;color:var(--muted2);margin-top:2px;">'+mn.lbl+' — '+mn.els.join(' ')+'</div></div><span class="mn-badge" style="background:'+mn.col+'22;color:'+mn.col+';">'+mn.lbl+'</span></div><div class="mn-body"><div class="mn-phrase">'+mn.text+'</div><div class="mn-hindi">🇮🇳 '+mn.hindi+'</div><div class="mn-explanation">'+mn.meaning+'</div><div class="mn-btns"><button class="mn-btn mn-play" id="mnPlay'+i+'" onclick="playMn('+i+')">▶ Play Hindi Audio</button><button class="mn-btn mn-hl" onclick="hlMn('+i+')">✨ Highlight on Table</button></div><div class="mn-prog"><div class="mn-prog-fill" id="mnPF'+i+'"></div></div></div></div>';
  }).join('');
}
buildMn();
function playMn(i){
  var mn=mnData[i];var btn=document.getElementById('mnPlay'+i);var pf=document.getElementById('mnPF'+i);
  if(mnVA[i]&&window.speechSynthesis.speaking){window.speechSynthesis.cancel();btn.textContent='▶ Play Hindi Audio';btn.classList.remove('playing');mnVA[i]=false;return;}
  stopSpeech();Object.keys(mnVA).forEach(function(k){mnVA[k]=false;var b=document.getElementById('mnPlay'+k);if(b){b.textContent='▶ Play Hindi Audio';b.classList.remove('playing');}});
  var utt=new SpeechSynthesisUtterance(mn.hindi);
  function go(){
    var voices=window.speechSynthesis.getVoices();
    var hv=voices.find(function(v){return v.lang==='hi-IN'||v.lang==='hi'||v.name.includes('Hindi')||v.name.includes('Hemant')||v.name.includes('Lekha');});
    if(hv){utt.voice=hv;utt.lang='hi-IN';}else{utt.lang='hi-IN';}
    utt.rate=0.82;utt.pitch=0.92;utt.volume=1;
    var st=Date.now();var tot=mn.hindi.length*95;
    utt.onstart=function(){btn.classList.add('playing');btn.textContent='⏸ Pause / Stop';mnVA[i]=true;var itv=setInterval(function(){if(!mnVA[i]){clearInterval(itv);return;}var pct=Math.min(98,(Date.now()-st)/tot*100);if(pf)pf.style.width=pct+'%';},120);};
    utt.onend=utt.onerror=function(){btn.classList.remove('playing');btn.textContent='▶ Play Hindi Audio';mnVA[i]=false;if(pf){pf.style.width='100%';setTimeout(function(){pf.style.width='0%';},800);}};
    window.speechSynthesis.speak(utt);
  }
  if(window.speechSynthesis.getVoices().length===0){window.speechSynthesis.onvoiceschanged=go;}else{go();}
}
function hlMn(i){
  var mn=mnData[i];
  clearCat();
  document.querySelectorAll('.cell[data-n]').forEach(function(c){c.classList.add('dim');});
  mn.nums.forEach(function(n){var c=document.querySelector('.cell[data-n="'+n+'"]');if(c){c.classList.remove('dim');c.style.boxShadow='0 0 18px '+mn.col+', 0 0 36px '+mn.col+'66';c.style.transform='scale(1.14)';c.style.border='2px solid '+mn.col;c.style.zIndex='25';}});
  sv('tblView',document.querySelector('.ntab'));showToast(mn.grp+' highlighted on the periodic table!');
  setTimeout(function(){document.querySelectorAll('.cell[data-n]').forEach(function(c){c.classList.remove('dim');c.style.boxShadow='';c.style.transform='';c.style.border='';c.style.zIndex='';});},5000);
}

// ===== NCERT =====
var ncertContent={
  mole:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Mole Concept</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 11 — Chapter 1: Some Basic Concepts of Chemistry</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">⚛</div><div class="cc-title">The Mole</div><div class="cc-body">1 mole = <b>6.022 × 10²³</b> particles (Avogadro\'s number, Nₐ).<br>Mass of 1 mole C-12 = exactly 12 grams.</div><code class="cc-formula">Moles = Mass (g) / Molar Mass (g/mol)</code></div><div class="concept-card"><div class="cc-icon">⚖️</div><div class="cc-title">Molar Mass</div><div class="cc-body">Numerically equal to atomic/molecular mass in u.<br>H₂O: 2(1) + 16 = <b>18 g/mol</b><br>NaCl: 23 + 35.5 = <b>58.5 g/mol</b></div></div><div class="concept-card"><div class="cc-icon">🧪</div><div class="cc-title">Concentration</div><div class="cc-body"><b>Molarity (M):</b> mol/L solution<br><b>Molality (m):</b> mol/kg solvent<br><b>Mole fraction (X):</b> nₐ/(nₐ+n_b)</div><code class="cc-formula">M = n / V(L)</code></div><div class="concept-card"><div class="cc-icon">⚗</div><div class="cc-title">Stoichiometry</div><div class="cc-body">Coefficients give molar ratios:<br>N₂ + 3H₂ → 2NH₃<br>1 mol N₂ : 3 mol H₂ : 2 mol NH₃<br>Limiting reagent → consumed first.</div></div></div>',
  thermo:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Thermodynamics</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 11 — Chapter 6</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">🌡️</div><div class="cc-title">First Law</div><div class="cc-body">Energy is conserved: <b>ΔU = q + w</b><br>At constant pressure: <b>ΔH = qₚ</b><br>Exothermic: ΔH < 0 | Endothermic: ΔH > 0</div></div><div class="concept-card"><div class="cc-icon">📉</div><div class="cc-title">Gibbs Energy</div><div class="cc-body">Spontaneous if ΔG < 0:<br><b>ΔG = ΔH − TΔS</b><br>Entropy (S) = measure of disorder.<br>ΔS_universe > 0 (spontaneous).</div></div><div class="concept-card"><div class="cc-icon">🧊</div><div class="cc-title">Hess\'s Law</div><div class="cc-body">ΔH_rxn = ΣΔH_f(products) − ΣΔH_f(reactants)<br>Path-independent — use thermochemical cycles.</div></div><div class="concept-card"><div class="cc-icon">🔥</div><div class="cc-title">Bond Enthalpy</div><div class="cc-body">ΔH_rxn = Σ(bonds broken) − Σ(bonds formed)<br>Bond breaking = endothermic<br>Bond forming = exothermic</div></div></div>',
  equil:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Chemical Equilibrium</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 11 — Chapter 7</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">⚖️</div><div class="cc-title">Dynamic Equilibrium</div><div class="cc-body">Rate<sub>forward</sub> = Rate<sub>backward</sub><br>Concentrations remain constant. System is reversible (⇌).</div></div><div class="concept-card"><div class="cc-icon">📐</div><div class="cc-title">Equilibrium Constant</div><div class="cc-body">For aA + bB ⇌ cC + dD:<br>K_c = [C]ᶜ[D]ᵈ / [A]ᵃ[B]ᵇ<br>Large Kc → products favoured.</div><code class="cc-formula">Kp = Kc(RT)^Δn</code></div><div class="concept-card"><div class="cc-icon">⚗</div><div class="cc-title">Le Chatelier\'s Principle</div><div class="cc-body">System shifts to oppose disturbance:<br>• ↑ [reactant] → shifts right<br>• ↑ pressure → fewer moles of gas side<br>• ↑ temp → endothermic side</div></div><div class="concept-card"><div class="cc-icon">🧪</div><div class="cc-title">Acids & Bases</div><div class="cc-body">Arrhenius: H⁺ / OH⁻<br>Brønsted-Lowry: proton donor/acceptor<br>Lewis: electron pair acceptor/donor<br>pH = −log[H⁺]</div></div></div>',
  named:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Named Reactions</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 12 Organic Chemistry — Must Know</p><table class="ncert-table"><thead><tr><th>Reaction</th><th>Equation</th><th>Key Note</th></tr></thead><tbody><tr><td>Haber Process</td><td style="font-family:var(--mono);font-size:10px;">N₂ + 3H₂ ⇌ 2NH₃</td><td>Fe catalyst, 400°C, 200 atm</td></tr><tr><td>Contact Process</td><td style="font-family:var(--mono);font-size:10px;">2SO₂ + O₂ → 2SO₃ → H₂SO₄</td><td>V₂O₅, 450°C</td></tr><tr><td>Aldol Condensation</td><td style="font-family:var(--mono);font-size:10px;">2CH₃CHO → CH₃CHOHCH₂CHO</td><td>Dilute NaOH, cold</td></tr><tr><td>Cannizzaro Reaction</td><td style="font-family:var(--mono);font-size:10px;">2HCHO + NaOH → HCOO⁻ + CH₃OH</td><td>Non-enolizable aldehydes only</td></tr><tr><td>Reimer-Tiemann</td><td style="font-family:var(--mono);font-size:10px;">PhOH + CHCl₃ + NaOH → 2-HOPhCHO</td><td>Introduces –CHO at ortho position</td></tr><tr><td>Kolbe\'s Reaction</td><td style="font-family:var(--mono);font-size:10px;">PhONa + CO₂ → salicylic acid</td><td>Aspirin precursor</td></tr><tr><td>Sandmeyer\'s</td><td style="font-family:var(--mono);font-size:10px;">ArN₂⁺ + CuX → ArX + N₂</td><td>Diazonium → aryl halide</td></tr><tr><td>Wurtz Reaction</td><td style="font-family:var(--mono);font-size:10px;">2R-X + 2Na → R-R + 2NaX</td><td>Dry ether, symmetrical alkanes</td></tr><tr><td>Grignard</td><td style="font-family:var(--mono);font-size:10px;">R-X + Mg → RMgX (dry ether)</td><td>Most versatile C–C bond formation</td></tr><tr><td>Friedel-Crafts</td><td style="font-family:var(--mono);font-size:10px;">C₆H₆ + RCl → C₆H₅R + HCl</td><td>AlCl₃ catalyst (EAS)</td></tr></tbody></table>',
  hybrid:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Hybridization & VSEPR</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 11 — Chapter 4: Chemical Bonding</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">📐</div><div class="cc-title">sp³ Hybridization</div><div class="cc-body"><b>Shape:</b> Tetrahedral (109.5°)<br>CH₄: 4bp → tetrahedral<br>NH₃: 3bp+1lp → pyramidal<br>H₂O: 2bp+2lp → bent (104.5°)</div></div><div class="concept-card"><div class="cc-icon">🔺</div><div class="cc-title">sp² Hybridization</div><div class="cc-body"><b>Shape:</b> Trigonal planar (120°)<br>BF₃, C₂H₄, HCHO<br>One empty p orbital → π bond<br>BF₃ is Lewis acid</div></div><div class="concept-card"><div class="cc-icon">➡️</div><div class="cc-title">sp Hybridization</div><div class="cc-body"><b>Shape:</b> Linear (180°)<br>BeCl₂, CO₂, C₂H₂<br>Two p orbitals → two π bonds<br>Triple bond in alkynes</div></div><div class="concept-card"><div class="cc-icon">🎯</div><div class="cc-title">VSEPR Theory</div><div class="cc-body">Electron pairs repel → arrange to minimize repulsion.<br>Lone pair > bonding pair repulsion.<br>SO₂: bent (119°), PCl₅: trigonal bipyramidal</div></div></div>',
  bonding:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Chemical Bonding</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 11 — Chapter 4</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">⊕⊖</div><div class="cc-title">Ionic Bond</div><div class="cc-body">Electron <b>transfer</b> from metal to nonmetal.<br>Na → Na⁺ + e⁻; Cl + e⁻ → Cl⁻<br>NaCl lattice energy = 787 kJ/mol<br>High IE + high EA → ionic bond</div></div><div class="concept-card"><div class="cc-icon">🔗</div><div class="cc-title">Covalent Bond</div><div class="cc-body">Electron <b>sharing</b> between nonmetals.<br>H-H, O=O, N≡N<br>Bond order ↑ → shorter + stronger<br>Polar if EN difference 0.5–1.7</div></div><div class="concept-card"><div class="cc-icon">🌊</div><div class="cc-title">Resonance</div><div class="cc-body">Multiple equivalent Lewis structures.<br>O₃: bond order = 1.5<br>Benzene: all bonds equal (1.5)<br>Resonance → extra stability</div></div><div class="concept-card"><div class="cc-icon">💧</div><div class="cc-title">Hydrogen Bonding</div><div class="cc-body">Between H (on F,O,N) and lone pair of F,O,N.<br>H₂O high BP due to H-bonding<br>DNA double helix — H-bonds<br>Intramolecular: o-nitrophenol</div></div></div>',
  pblock:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">p-Block Elements</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 11 Ch 11 & 12 | Class 12 Ch 7 & 8</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">🟦</div><div class="cc-title">Group 15 (N family)</div><div class="cc-body">Config: ns²np³ — half-filled p³ stable!<br>N₂: triple bond = 945 kJ/mol<br>NH₃: pyramidal (1 lone pair)<br>HNO₃ via Ostwald process</div></div><div class="concept-card"><div class="cc-icon">🟨</div><div class="cc-title">Group 16 (O family)</div><div class="cc-body">O₃ bent (117°), paramagnetic O₂ (2 unpaired e⁻)<br>Contact process: SO₂→SO₃ (V₂O₅)<br>SF₆: hypervalent (sp³d²)</div></div><div class="concept-card"><div class="cc-icon">🟧</div><div class="cc-title">Group 17 (Halogens)</div><div class="cc-body">Reactivity: F > Cl > Br > I<br>HF weak acid (strong H-F bond)<br>Displacement: Cl₂+2KBr→2KCl+Br₂<br>Oxoacid strength: HClO < HClO₄</div></div><div class="concept-card"><div class="cc-icon">🔵</div><div class="cc-title">Group 18 (Noble Gases)</div><div class="cc-body">Complete shells — very inert.<br>XeF₂ (linear), XeF₄ (square planar)<br>Used in MRI, welding, signs<br>He: lowest BP of all elements</div></div></div>',
  dblock:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">d & f Block Elements</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 12 — Chapter 8</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">🔩</div><div class="cc-title">General Properties</div><div class="cc-body">• Variable oxidation states (multiple d e⁻)<br>• Coloured ions (d-d transitions)<br>• Paramagnetic (unpaired d e⁻)<br>• Excellent catalysts<br>• High melting points</div></div><div class="concept-card"><div class="cc-icon">🎨</div><div class="cc-title">Colour of Ions</div><div class="cc-body">Cu²⁺: Blue (3d⁹) | Fe³⁺: Yellow (3d⁵)<br>Cr³⁺: Violet (3d³) | Mn²⁺: Pink (3d⁵)<br>Zn²⁺: Colourless (3d¹⁰ full!)</div></div><div class="concept-card"><div class="cc-icon">⚗</div><div class="cc-title">Important Catalysts</div><div class="cc-body">Fe → Haber process (N₂+3H₂→2NH₃)<br>V₂O₅ → Contact process<br>Ni/Pt/Pd → hydrogenation<br>MnO₂ → KClO₃ decomposition</div></div><div class="concept-card"><div class="cc-icon">📍</div><div class="cc-title">Lanthanide Contraction</div><div class="cc-body">Atomic radius decreases across lanthanides.<br>Poor shielding by 4f electrons.<br>Affects Period 6 transition metals.<br>Explains similar sizes of Zr & Hf.</div></div></div>',
  coord:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Coordination Compounds</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 12 — Chapter 9</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">🔵</div><div class="cc-title">Werner\'s Theory</div><div class="cc-body">[Co(NH₃)₆]³⁺: Co is central metal, NH₃ = ligands.<br>Coordination number = 6<br>IUPAC: tetraamminecopper(II) sulfate</div></div><div class="concept-card"><div class="cc-icon">🔗</div><div class="cc-title">Types of Ligands</div><div class="cc-body">Monodentate: NH₃, Cl⁻, H₂O (1 donor)<br>Bidentate: en, oxalate (2 donors)<br>Polydentate: EDTA⁴⁻ (6 donors)<br>Ambidentate: SCN⁻, NO₂⁻</div></div><div class="concept-card"><div class="cc-icon">⚡</div><div class="cc-title">Crystal Field Theory</div><div class="cc-body">Ligands split d orbitals → t₂g & eₘ<br>Strong field → large Δ → low spin<br>Spectrochemical series:<br>I⁻ < Cl⁻ < OH⁻ < H₂O < NH₃ < CN⁻</div></div><div class="concept-card"><div class="cc-icon">🔄</div><div class="cc-title">Isomerism</div><div class="cc-body">Structural: ionisation, linkage, hydrate<br>Geometrical: cis-trans (square planar, octahedral)<br>Optical: non-superimposable mirror images</div></div></div>',
  redox:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Redox Reactions</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 11 — Chapter 8</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">⚡</div><div class="cc-title">OIL RIG</div><div class="cc-body"><b>O</b>xidation <b>I</b>s <b>L</b>oss (of electrons)<br><b>R</b>eduction <b>I</b>s <b>G</b>ain (of electrons)<br>Oxidizing agent: gains e⁻ (gets reduced)<br>Reducing agent: loses e⁻ (gets oxidized)</div></div><div class="concept-card"><div class="cc-icon">📊</div><div class="cc-title">Oxidation States</div><div class="cc-body">Free element: 0 | Monatomic ion: = charge<br>O usually −2 (−1 in H₂O₂)<br>H usually +1 (−1 in metal hydrides)<br>Sum in neutral molecule = 0</div></div><div class="concept-card"><div class="cc-icon">🔋</div><div class="cc-title">Balancing Redox</div><div class="cc-body">Half-reaction method:<br>1. Separate ox/red half-reactions<br>2. Balance atoms (H₂O for O, H⁺ for H)<br>3. Balance charge (add e⁻)<br>4. Multiply & combine</div></div></div>',
  electro:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Electrochemistry</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 12 — Chapter 3</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">🔋</div><div class="cc-title">Galvanic Cell</div><div class="cc-body">Zn | Zn²⁺ || Cu²⁺ | Cu (Daniel cell)<br>Anode: Zn → Zn²⁺ + 2e⁻ (oxidation)<br>Cathode: Cu²⁺ + 2e⁻ → Cu (reduction)<br>Cell EMF = E°(cathode) − E°(anode)</div></div><div class="concept-card"><div class="cc-icon">📐</div><div class="cc-title">Nernst Equation</div><div class="cc-body">At 25°C:<br>E = E° − (0.0592/n) log Q<br>At equilibrium: E=0, log K = nE°/0.0592</div><code class="cc-formula">E = E° − (RT/nF) ln Q</code></div><div class="concept-card"><div class="cc-icon">🧲</div><div class="cc-title">Faraday\'s Laws</div><div class="cc-body">1st Law: m ∝ Q (charge passed)<br>2nd Law: m₁/m₂ = E₁/E₂<br>1 Faraday = 96485 C<br>m = (M/nF) × I × t</div></div><div class="concept-card"><div class="cc-icon">⚡</div><div class="cc-title">Conductance</div><div class="cc-body">Λm = κ × 1000/C<br>Strong electrolytes: Λm = Λ°m − A√C<br>Kohlrausch Law: Λ°m = Σλ_ions<br>κ (conductivity) increases with temp.</div></div></div>',
  kinetics:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Chemical Kinetics</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 12 — Chapter 4</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">⏱️</div><div class="cc-title">Rate of Reaction</div><div class="cc-body">Rate = k[A]ᵐ[B]ⁿ<br>Order = m + n (experimental)<br>Rate constant k depends on T<br>Half-life: t½ = 0.693/k (1st order)</div></div><div class="concept-card"><div class="cc-icon">📈</div><div class="cc-title">Arrhenius Equation</div><div class="cc-body">k = Ae^(−Eₐ/RT)<br>Eₐ = activation energy<br>A = frequency factor<br>Higher T → larger k → faster reaction</div><code class="cc-formula">ln k = ln A − Eₐ/RT</code></div><div class="concept-card"><div class="cc-icon">🔬</div><div class="cc-title">Collision Theory</div><div class="cc-body">Rate = Ze^(−Eₐ/RT)<br>Z = collision frequency<br>Effective collision = correct orientation + E ≥ Eₐ<br>Catalyst: provides alternate pathway with lower Eₐ</div></div></div>',
  hydro:'<div style="font-size:20px;font-weight:800;margin-bottom:4px;">Hydrocarbons</div><p style="font-size:12px;color:var(--muted);margin-bottom:16px;">Class 11 Ch 13 | Class 12 Organic</p><div class="concept-grid"><div class="concept-card"><div class="cc-icon">⛽</div><div class="cc-title">Alkanes (CₙH₂ₙ₊₂)</div><div class="cc-body">sp³, 109.5°, sigma bonds only<br>Combustion + halogenation (UV)<br>Free radical mechanism<br>CH₄ → CH₃Cl → CH₂Cl₂ → CHCl₃ → CCl₄</div></div><div class="concept-card"><div class="cc-icon">🔗</div><div class="cc-title">Alkenes (CₙH₂ₙ)</div><div class="cc-body">sp², 120°, contains C=C<br>Electrophilic addition<br>Bromine test (decolourises)<br>Markovnikov rule for HX addition</div></div><div class="concept-card"><div class="cc-icon">⚡</div><div class="cc-title">Alkynes (CₙH₂ₙ₋₂)</div><div class="cc-body">sp, 180°, contains C≡C<br>More reactive than alkenes<br>HC≡CH + H₂O → CH₃CHO (Kucherov)<br>Terminal H is weakly acidic (pKa~25)</div></div><div class="concept-card"><div class="cc-icon">⬡</div><div class="cc-title">Benzene (Aromatic)</div><div class="cc-body">sp², 120°, all bonds = 140 pm<br>6π electrons (Hückel: 4n+2 rule)<br>EAS: nitration, halogenation, FC<br>Resonance energy = 150 kJ/mol</div></div></div>',
};
function showNCERT(key){document.querySelectorAll('.ncert-link').forEach(function(b){b.classList.toggle('on',b.getAttribute('onclick').includes("'"+key+"'"));});var content=ncertContent[key];if(content)document.getElementById('ncertContent').innerHTML=content;else document.getElementById('ncertContent').innerHTML='<div style="padding:20px;color:var(--muted);">Content coming soon.</div>';}

// ===== IONS =====
var ions={mono:[{f:'H⁺',n:'Hydrogen',c:'+1',bg:'#eff6ff'},{f:'Na⁺',n:'Sodium',c:'+1',bg:'#ffe4e6'},{f:'K⁺',n:'Potassium',c:'+1',bg:'#ffe4e6'},{f:'Li⁺',n:'Lithium',c:'+1',bg:'#ffe4e6'},{f:'Ag⁺',n:'Silver',c:'+1',bg:'#fef3c7'},{f:'Mg²⁺',n:'Magnesium',c:'+2',bg:'#ffedd5'},{f:'Ca²⁺',n:'Calcium',c:'+2',bg:'#ffedd5'},{f:'Ba²⁺',n:'Barium',c:'+2',bg:'#ffedd5'},{f:'Zn²⁺',n:'Zinc',c:'+2',bg:'#f3f4f6'},{f:'Al³⁺',n:'Aluminium',c:'+3',bg:'#e0e7ff'},{f:'F⁻',n:'Fluoride',c:'−1',bg:'#ecfdf5'},{f:'Cl⁻',n:'Chloride',c:'−1',bg:'#ecfdf5'},{f:'Br⁻',n:'Bromide',c:'−1',bg:'#ecfdf5'},{f:'I⁻',n:'Iodide',c:'−1',bg:'#ecfdf5'},{f:'O²⁻',n:'Oxide',c:'−2',bg:'#cffafe'},{f:'S²⁻',n:'Sulfide',c:'−2',bg:'#cffafe'},{f:'N³⁻',n:'Nitride',c:'−3',bg:'#ede9fe'},{f:'P³⁻',n:'Phosphide',c:'−3',bg:'#ede9fe'}],
poly:[{f:'CO₃²⁻',n:'Carbonate',c:'−2',bg:'#f0fdf4'},{f:'NO₃⁻',n:'Nitrate',c:'−1',bg:'#f0fdf4'},{f:'NO₂⁻',n:'Nitrite',c:'−1',bg:'#f0fdf4'},{f:'SO₄²⁻',n:'Sulfate',c:'−2',bg:'#fff7ed'},{f:'SO₃²⁻',n:'Sulfite',c:'−2',bg:'#fff7ed'},{f:'PO₄³⁻',n:'Phosphate',c:'−3',bg:'#f5f3ff'},{f:'ClO₄⁻',n:'Perchlorate',c:'−1',bg:'#fefce8'},{f:'ClO⁻',n:'Hypochlorite',c:'−1',bg:'#fefce8'},{f:'NH₄⁺',n:'Ammonium',c:'+1',bg:'#eff6ff'},{f:'OH⁻',n:'Hydroxide',c:'−1',bg:'#cffafe'},{f:'HCO₃⁻',n:'Bicarbonate',c:'−1',bg:'#f0fdf4'},{f:'HSO₄⁻',n:'Bisulfate',c:'−1',bg:'#fff7ed'}],
trans:[{f:'Cu⁺',n:'Copper(I)',c:'+1',bg:'#fff7ed'},{f:'Cu²⁺',n:'Copper(II)',c:'+2',bg:'#fff7ed'},{f:'Fe²⁺',n:'Iron(II)',c:'+2',bg:'#f3f4f6'},{f:'Fe³⁺',n:'Iron(III)',c:'+3',bg:'#f3f4f6'},{f:'Pb²⁺',n:'Lead(II)',c:'+2',bg:'#f3f4f6'},{f:'MnO₄⁻',n:'Permanganate',c:'−1',bg:'#fdf4ff'},{f:'CrO₄²⁻',n:'Chromate',c:'−2',bg:'#fefce8'},{f:'Cr₂O₇²⁻',n:'Dichromate',c:'−2',bg:'#fff7ed'},{f:'Hg²⁺',n:'Mercury(II)',c:'+2',bg:'#f0fdf4'}],
special:[{f:'CN⁻',n:'Cyanide',c:'−1',bg:'#ffe4e6'},{f:'SCN⁻',n:'Thiocyanate',c:'−1',bg:'#f3f4f6'},{f:'CH₃COO⁻',n:'Acetate',c:'−1',bg:'#ecfdf5'},{f:'RCOO⁻',n:'Carboxylate',c:'−1',bg:'#f0fdf4'},{f:'C₂O₄²⁻',n:'Oxalate',c:'−2',bg:'#f0fdf4'},{f:'H₂PO₄⁻',n:'Dihydrogen phosphate',c:'−1',bg:'#f5f3ff'}]};
function buildIons(){
  function rnd(id,list){document.getElementById(id).innerHTML=list.map(function(ion){return'<div class="ion-card" style="background:'+ion.bg+'"><div class="ion-f">'+ion.f+'</div><div class="ion-name">'+ion.n+'</div><div class="ion-badge2">'+ion.c+'</div></div>';}).join('');}
  rnd('ionMono',ions.mono);rnd('ionPoly',ions.poly);rnd('ionTrans',ions.trans);rnd('ionSpecial',ions.special);
}
buildIons();
